/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alternativetags.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_statuscolors.h"
#include "bar_winicon.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "aspectresize.h"
#include "attachx.h"
#include "cool_autostart.h"
#include "cyclelayouts.h"
#include "dragmfact.h"
#include "focusmaster.h"
#include "keymodes.h"
#include "killunsel.h"
#include "moveresize.h"
#include "pertag.h"
#include "placemouse.h"
#include "restartsig.h"
#include "rotatestack.h"
#include "renamed_scratchpads.h"
#include "seamless_restart.h"
#include "setborderpx.h"
#include "shift.h"
#include "shiftboth.h"
#include "shiftview.h"
#include "shiftviewclients.h"
#include "sticky.h"
#include "swapfocus.h"
#include "togglefullscreen.h"
#include "toggletopbar.h"
#include "vanitygaps.h"
#include "zoomswap.h"
#include "xresources.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_monocle.h"
#include "layout_tile.h"

