/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alternativetags.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_statuscolors.c"
#include "bar_winicon.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "aspectresize.c"
#include "attachx.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "focusmaster.c"
#include "keymodes.c"
#include "killunsel.c"
#include "moveresize.c"
#include "pertag.c"
#include "placemouse.c"
#include "restartsig.c"
#include "rotatestack.c"
#include "renamed_scratchpads.c"
#include "setborderpx.c"
#include "shift.c"
#include "shiftboth.c"
#include "shiftview.c"
#include "shiftviewclients.c"
#include "sticky.c"
#include "swapfocus.c"
#include "togglefullscreen.c"
#include "toggletopbar.c"
#include "vanitygaps.c"
#include "zoomswap.c"
#include "xresources.c"
#include "dragmfact.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_monocle.c"
#include "layout_tile.c"

